### ISSUE TITLE
Keywords are allowed as record labels currently

### ISSUE THREAD

**Issue by hdgarrood** [natefaubion/purescript-cst#3]
The following expression is allowed by the compiler, but does not parse with the cst parser:

```
{ type: 0 }
```

**Comment by natefaubion** [comment]
This is because record literals are parsed as expressions, to get around conflicts regarding `:` as an operator.
https://github.com/natefaubion/purescript-cst/blob/55cc6b29df163491042a93fb75e24dd3313a9779/src/Language/PureScript/CST/Parser.y#L352

There may be an alternative way to get around the conflict, but the most straightforward way would probably be to just allow keywords in identifier position it, and deal with the errors during name resolution since that has to be done anyway. I'd like to avoid doing a pass like that twice if I can't deal with it in the grammar.

**Comment by natefaubion** [comment]
One way to formulate this rule is to have two `label` forms, one that includes identifiers, and one that includes all the keywords. Since they wouldn't overlap, it should be possible to handle this with:
```
recordLabel :: { RecordLabeled (Expr ()) }
: labelkw ':' expr { ... }
| expr {% toRecordLabeled $1 }
```
