### ISSUE TITLE
Failure on purescript-string-parsers

### ISSUE THREAD

**Issue by hdgarrood** [natefaubion/purescript-cst#7]
> Unexpected or mismatched indentation at line 51, column 7

See https://github.com/purescript-contrib/purescript-string-parsers/blob/098c22d9c8b62fb6c67ac62ccb6610720cf71810/src/Text/Parsing/StringParser/Expr.purs#L36-L57

I'm not sure what the problem is here, exactly, or whether this is something which should be allowed.

**Comment by natefaubion** [comment]
Minimal test:
```purescript
module Test where

test =
  let
    a =
      let b = 12
      in b
  in
    a
```
With explicit delimiters you can see that for some reason the layout algorithm is inserting an additional closing layout before the `in` in the nested let.
```purescript
module Test where{

test =
  let{
    a =
      let{ b = 12}}
      in b
  in
    a}
```

I think this is because there are two rules to insert closing layout which get triggered.
  * `in` is indented less than `b`, so it's inserted
  * `in` is considered a closing delimiter for `let`, so it's inserted

This happens in the nested let case here because `let` is at the top of the layout stack in both cases, even though they are different lets. I think instead of running both checks, we need to run either of them.

**Comment by natefaubion** [comment]
This particular case has been fixed, but developing a comprehensive layout algorithm is still ongoing.
